name: Lint

on: [push, pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "88"
