# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2023 Linutronix GmbH

name: "E.L.B.E. license check"

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - 'devel/**'
  pull_request:
    branches:
      - master
      - 'devel/**'

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  run-reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt-get install -y reuse

    - name: Run license check
      run: reuse lint
